### ISSUE TITLE
Empty error response in some plugin

### ISSUE THREAD

**Issue by jihyungSong** [cloudforet-io/plugin-aws-phd-inven-collector#4]
### Discussed in https://github.com/cloudforet-io/community/discussions/75

<div type='discussions-op-text'>

<sup>Originally posted by **gikang82** December 15, 2022</sup>
Hello I`m using SpaceONE service, but there is a empty error message from some collector

I`m using 'AWS Personal Health Dashboard Collector' there is a error message while executing collector

`No message from plugin`

Is there any possible reason to that message?
Usually plugin returns readable error message but it seems like a exceptional case

</div>

**Comment by jihyungSong** [comment]
If an error occurs while collecting data from Plugin, it must be delivered to Inventory in the form of an ErrorResource. 
At this time, the `message` value should be delivered, but the `message` value is missing due to a plugin bug. 
This issue has now been resolved.

![스크린샷 2022-12-20 오후 1 36 50](https://user-images.githubusercontent.com/7124443/208584812-07957b7a-19ec-47fb-a185-710b80b87f2f.png)

**Comment by jihyungSong** [comment]
Release: [v1.4.6](https://github.com/cloudforet-io/plugin-aws-phd-inven-collector/releases/tag/v1.4.6)

**Comment by gikang82** [comment]
Thanks! 👍
